apiVersion: v1
kind: Pod
metadata:
  name: spot-pod
spec:
  containers:
  - name: spot-pod-con
    image: busybox
    command:
      - /bin/sh
      - "-c"
      - "sleep infinity"
  tolerations:
  - key: "kubernetes.azure.com/scalesetpriority"
    operator: "Equal"
    value: "spot"
    effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "kubernetes.azure.com/scalesetpriority"
            operator: In
            values:
            - "spot"